apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyber-power-ups
spec:
  selector:
    matchLabels:
      app: cyber-power-ups
  template:
    metadata:
      labels:
        app: cyber-power-ups
    spec:
      containers:
      - name: cyber-power-ups
        image:  gabbersepp/cyber-power-ups-control
        imagePullPolicy: Always
        volumeMounts:
        - mountPath:  /dev/usb/hiddev1
          name: hid
        - mountPath: /config
          name: sambashare
          subPath: cyber-power-ups/config
        securityContext:
          privileged: true
      volumes:
      - name: hid
        hostPath:
          path:  /dev/usb/hiddev1
      - name: sambashare
        flexVolume:
          driver: "fstab/cifs"
          fsType: "cifs"
          secretRef:
            name: "cifs-secret"
          options:
            networkPath: "//192.168.2.126/sambashare"
            mountOptions: "uid=0"